#!/usr/bin/bash
yellow_bright="\[\033[01;33m\]"
green_bright="\[\033[01;32m\]"
blue_bright="\[\033[01;34m\]"
red_bright="\[\033[01;31m\]"
#purple_bright="\[\033[01;36m\]"
purple_bright="\[\033[01;36m\]"
yellow="\[\033[00;33m\]"
green="\[\033[00;32m\]"
blue="\[\033[00;34m\]"
red="\[\033[00;31m\]"
purple="\[\033[00;36m\]"
reset_color="\[\033[00m\]"

# Git handle
source ~/.config/git.zsh
GIT_RAW=$(git_prompt_info)
GIT_COUNT=""
GIT=""
if [[ "${#GIT_RAW}" -gt "0" ]]; then
	GIT_COUNT="< ${GIT_RAW} >"
	GIT="(${purple}${GIT_RAW}${green_bright})"
fi

# FIxes character calculus
NAMES="$USER@$HOSTNAME"
DATE=`date +%H:%M`
CWD=$(pwd)
FIXED_HOME=${#CWD}
if [[ "${CWD}" == $(eval 'echo ~')* ]]; then
	EXP=$(eval 'echo ~')
	FIXED_HOME=$((${#CWD}-${#EXP}+1))
fi
RAW_HEAD="╭─(${NAMES} ${DATE} )"
HEAD="${green}╭─${green_bright}(${NAMES}${yellow_bright} ${DATE} ${blue_bright}\w${green_bright})${GIT}"
RAW_END="╰─\$ "
END="${green}╰─${green_bright}\$${reset_color} "

#n=$(($COLUMNS-${#RAW_HEAD}-${FIXED_HOME}-${#GIT_COUNT}))
#p=""
# Bad way
#for i in `seq $n`; do p="${p}"`printf "─"`; done
# export PS1="${HEAD}${green}${p}"${TRAIL}"\n${END}"
export PS1="${HEAD}${green}${p}""\n${END}"

# clean
unset yellow_bright green_bright blue_bright red_bright yellow green blue red reset_color 
unset NAMES DATE CWD RAW_HEAD HEAD RAW_END END FIXED_HOME EXP GIT_RAW GIT_COUNT GIT n p i
# Clean git handle
unset DISABLE_UNTRACKED_FILES_DIRTY ZSH_THEME_GIT_PROMPT_DIRTY ZSH_THEME_GIT_PROMPT_CLEAN git_prompt_info parse_git_dirty
