#!/bin/bash

function get_layout() {
  echo $(setxkbmap -query | grep layout | awk '{ print $2 }')
}

function get_base_layout() {
  echo $(localectl status | sed -n -e 's/X11 Layout:\(.*\)$/\1/p' | tr -d ' ')
}

function set_layout() {
  local layout=$1; shift
  setxkbmap $layout
}

# allow toggling between current layout and spanish
# sometimes gb, sometimes us layout
prev_layout=$(get_base_layout)
base_layout="es"

if [[ "$(get_layout)" =~ "${base_layout}" ]]; then
  set_layout $prev_layout
else
  set_layout $base_layout
fi

